### ISSUE TITLE
Alter title to something more searchable

### ISSUE THREAD

**Issue by wdcurry** [rpendleton/xcode-canvas-color#1]
awesome! thanks Ryan.. 

Superb effort... one suggestion: alter the title to something more searchable? Like "xcode IB background" or "Xcode Interface Builder IB Background"

.. this will help it get more traction!  kudos ..

**Comment by rpendleton** [comment]
All of my repositories follow a naming convention, which explains the name of this one. That being said, I don't know that changing the name of it would help discovery at all. Odds are, I'd end up competing against people who are searching for how to change the background color of a view in storyboard.
