### ISSUE TITLE
Color not setting. Missing a step?

### ISSUE THREAD

**Issue by Sexadegen** [rpendleton/xcode-canvas-color#6]
I've installed the plug-in using Alcatraz and I've updated the plug-in's UUID list

```
<key>DVTPlugInCompatibilityUUIDs</key>
<array>
    <string>C4A681B0-4A26-480E-93EC-1218098B9AA0</string>
    <string>A16FF353-8441-459E-A50C-B071F53F51B7</string>
    <string>9F75337B-21B4-4ADC-B558-F9CADF7073A7</string>
    <string>E969541F-E6F9-4D25-8158-72DC3545A6C6</string>
    <string>7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90</string>
    <string>0420B86A-AA43-4792-9ED0-6FE0F2B16A13</string>
    <string>7265231C-39B4-402C-89E1-16167C4CC990</string>
    <string>F41BD31E-2683-44B8-AE7F-5F09E919790E</string>
            <string>ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C</string>
</array>
```

But I see no change when I open Xcode. I've tried rebooting but I'm still stuck with the white storyboard canvas. Am I missing a step? Thanks.

**Comment by rpendleton** [comment]
Do you see any messages in console indicating that Xcode didn't load it?

**Comment by rpendleton** [comment]
I updated the Info.plist in the project and installed the plugin via Alcatraz, and can verify that the plugin is working as expected. Since there's been no response, I'm going to go ahead and close this issue.

**Comment by Sexadegen** [comment]
Hi Ryan,

Sorry for the lack of response. I didn’t get around to checking this.

Regards

Phil
