### ISSUE TITLE
Xcode 8 compatibility?

### ISSUE THREAD

**Issue by dburr** [rpendleton/xcode-canvas-color#7]
Any chance at getting this to work with Xcode 8? Should be coming out fairly soon now along with all the new OS's. I tried building the plugin using Xcode 8b6 and while it did build, it didn't work (no change in the Interface Builder canvas color. And yes I did add the DVTPlugInCompatibilityUUID from 8b6.

**Comment by rpendleton** [comment]
Unfortunately, this it out of my hands. Apple announced the following during this the 2016 WWDC:

> To further reinforce safety, Xcode is now secured by system integrity protection. Which means only trusted libraries and extensions can interact with the IDE and your code.

It looks like you may be able to circumvent this by removing the code signature on Xcode (see alcatraz/Alcatraz#475), but that's something I'm simply not comfortable instructing users to do.
